# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vasylpryimakawscourse
# "service" is the name of this project. This will also be added to your AWS resource names.
service: daily-inspiration-node

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"
      region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1
  stage: dev
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action: SNS:Publish
          Resource: "*"
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    REGION: ${self:provider.region}

functions:
  quotes:
    handler: handler/getQuotes.getQuotes
    events:
      - http:
          path: quotes
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
